version: '3'

services:
  bokeh:
    restart: always
    build:
      context: .
    image: prisma_vistool:master
    environment:
      BOKEH_PREFIX: ""
      PYTHONPATH: '/project'
      SHELL: '/bin/bash'

    ports:
      - '5006:5006'